name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile
      
      - name: Preprocess
        run: |
            ls $GITHUB_WORKSPACE/docs/go/
            echo "<GoogleAdsense/>" >> $GITHUB_WORKSPACE/docs/go/基础知识/*.md
            echo "<GoogleAdsense/>" >> $GITHUB_WORKSPACE/docs/go/进阶部分/*.md
            echo "<GoogleAdsense/>" >> $GITHUB_WORKSPACE/docs/go/*.md
            echo "<GoogleAdsense/>" >> $GITHUB_WORKSPACE/docs/java/*.md
            echo "<GoogleAdsense/>" >> $GITHUB_WORKSPACE/docs/python/*.md
            echo "<GoogleAdsense/>" >> $GITHUB_WORKSPACE/docs/whisper/*.md
        
      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WIKI_TOKEN }}
          keep_files: true
          publish_dir: docs/.vitepress/dist
          publish_branch: docs
